name: Build PHP docker images

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * SUN' # every sunday

jobs:

  build:
    name: PHP
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        php_version: ['7.2', '7.3', '7.4']

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ${{ matrix.php_version }}
        repository: lephare/php
        tags: ${{ matrix.php_version }}
