name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['5.4', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
    - name: PHP ${{ matrix.php_version }}
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ${{ matrix.php_version }}
        repository: lephare/php
        tags: ${{ matrix.php_version }}
