name: Build Unmaintained PHP images

on:
  push:
    branches:
        - unmaintained
  pull_request:
    branches:
        - unmaintained
  workflow_dispatch:

jobs:
  build:
    name: PHP
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php_version:
            # - '5.4'
            # - '5.6'
            # - '7.0'
            - '7.1'
            - '7.2'
            - '7.3'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: |
            linux/amd64
            linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: lephare/php
          tags: |
            type=raw,${{ matrix.php_version }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ matrix.php_version }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.setup-buildx.outputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
